title: Noah Keppers
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://noahkeppers.com" # the base hostname & protocol for your site, e.g. http://example.com

linkedin: "noah-keppers"
resume: "Keppers Resume.pdf"

collections:
  case_studies:
    output: true
    order:
      - theatre_engine.md
      - dancing_computer.md
      - ventra.md
      - queeries.md

plugins:
  - jekyll-seo-tag
